services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: sinalacs
      POSTGRES_PASSWORD: "ZGib82sxRnAaTto3iglbPkARA1qZUv0W"
    volumes:
      - sinalacs_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "xjjE2lgOgChcj15Gf5thYrjs1gzUoF4n"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: sinalacs_test
      POSTGRES_PASSWORD: "ehzaftIZDV8Ou4ILUIRsE02VhbjvBGZB"
    volumes:
      - sinalacs_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "b0Wa06K7wU5MZbrAdXk6VrRyvOtmsaWS"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  sinalacs_data:
  sinalacs_test_data:
