name: sinalacs_patient
description: Aplicativo do paciente do SinalACS.
publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  sqflite_sqlcipher: ^3.2.0
  connectivity_plus: ^7.3.1
  mqtt_client: ^10.0.0
  geolocator: ^12.0.0
  flutter_local_notifications: ^17.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
